ministryofjustice/prison-register

build.gradle.kts

includes springboot 2.6.1 and kotlin 1.6

DT-2999: ⬆️ Upgrade hmpps-gradle-springboot plugin to 4.0.0

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

includes springboot 2.6.2 and kotlin 1.6.10 and jvmTarget to 17

DT-3027: ⬆️ Upgrade hmpps-gradle-springboot plugin to 4.0.1

---

build.gradle.kts

HAAR-94: ⬆️ Upgrade hmpps-gradle-springboot plugin to 4.0.2

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/model/PrisonFilter.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/model/PrisonRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/resource/PrisonResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/service/PrisonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonregister/model/PrisonRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonregister/resource/PrisonResourceIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonregister/service/PrisonServiceTest.kt

https://dsdmoj.atlassian.net/browse/HAAR-30

HAAR-30: add getPrisonsFromActiveAndTextSearch endpoint

---

build.gradle.kts

https://dsdmoj.atlassian.net/browse/HAAR-164

HAAR-164: remove spring-cloud-starter-aws-messaging dependency

---

.circleci/config.yml
Dockerfile
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

and include CircleCi Jira Integration

HAAR-187: ⬆️ Upgrade hmpps-gradle-springboot plugin to 4.0.5-beta

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/model/PrisonType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/resource/PrisonResource.kt
src/main/resources/db/migration/V1_23__type.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonregister/resource/PrisonResourceIntTest.kt
src/test/resources/uk/gov/justice/digital/hmpps/prisonregister/resource/inserted_prison_with_address.json
src/test/resources/uk/gov/justice/digital/hmpps/prisonregister/resource/updated_prison.json

Addresses https://github.com/ministryofjustice/prison-register/issues/184

Her to His Majesty

---

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/model/PrisonRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/resource/PrisonResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/resource/model/PrisonRequest.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/prisonregister/service/PrisonService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/prisonregister/resource/PrisonResourceIntTest.kt

* New endpoint POST "/prisonsByIds"
* Returns list of prisons

1531 - Add new endpoint to fetch prisons by ids

---

src/main/resources/db/migration/V1_32__add_lthse_column.sql

First part of https://dsdmoj.atlassian.net/browse/MAP-1440

Add LTHSE boolean column

---

build.gradle.kts

[MAP-1562](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1562)
[MAP-1562]: https://dsdmoj.atlassian.net/browse/MAP-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1562 updated plugin dependency to fix CVE

---

build.gradle.kts
gradle.properties

[MAP-1570](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1570)
plus update other dependencies
[MAP-1570]: https://dsdmoj.atlassian.net/browse/MAP-1570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1570 updated plugin dependency to fix CVE

---

src/test/kotlin/uk/gov/justice/digital/hmpps/prisonregister/service/PrisonServiceTest.kt

I have covered these  scenarios
**Scenario 1 :** 
Before
After
**Scenario 2:** 
before
after

MAP-1458 PrisionService  findByPrisonFilter without textSearch without Active AND deleteEmailAddress ThrowNotFound true then NotFoundException 

---

build.gradle.kts

As part of the Alert duties , I have update dependency where have been possible.

Alert duties dependency update

---

src/test/kotlin/uk/gov/justice/digital/hmpps/prisonregister/service/PrisonServiceTest.kt

MAP-1458 CreateContactDetails test scenarios

---

.circleci/config.yml
Dockerfile

Hoping to fix
https://app.circleci.com/pipelines/github/ministryofjustice/prison-register/1827/workflows/e108f199-3dae-4c34-9dca-743d037e4825/jobs/4923?invite=true#step-111-12946_171

Use Jdk in Docker image + upgrade version of Hmpps orb

---

applicationinsights.dev.json
applicationinsights.json

See https://github.com/ministryofjustice/hmpps-template-kotlin/pull/204
https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config

Applied SDIT-1735: 🎨 Migrate sampling overrides

---

build.gradle.kts

Similar to #267 but keeping Jackson as-is otherwise it breaks the tests.
I tried to push the change to #267 but Renovate as being stubborn so opening a new PR instead

Renovate some Gradle minor dependencies

---

build.gradle.kts

minor dependency updates minus Jackson

---

build.gradle.kts

MAP-1842 Force version of netty common to fix security issue 

---

build.gradle.kts

but doing so the proper way ;-)

MAP 1842 Fix Netty security issue

---

renovate.json

https://github.com/ministryofjustice/prison-register/pull/301 did not succeed and we are still seeing Jackson in renovate PR
https://github.com/ministryofjustice/prison-register/pull/303

Trying to fix ignoring Jackson for Renovate

---

src/main/resources/db/migration/V1_38__add_welsh_prison_names_and_addresses.sql

[MAP-2047](https://dsdmoj.atlassian.net/browse/MAP-2047)
[MAP-2047]: https://dsdmoj.atlassian.net/browse/MAP-2047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-2047 migration to update name and addresses for welsh prisons
